name: qr
version: 0.5.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A demo of generating QR codes in Dart.
homepage: https://github.com/kevmoo/bot.dart
environment:
  sdk: '>=0.5.3'
dependencies:
  bot_web: '>=0.20.0'
  bot: '>=0.20.1'
dev_dependencies:
  hop: any
