name: qr
author: Kevin Moore <kevin@thinkpixellab.com>
description: A demo of generating QR codes in Dart.
homepage: https://github.com/kevmoo/bot.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.26.0'
  bot_web: '>=0.21.0'
dev_dependencies:
  bot_test: '>=0.1.5'
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.28.3+2'
