name: qr
author: Kevin Moore <kevin@thinkpixellab.com>
description: A demo of generating QR codes in Dart.
homepage: https://github.com/kevmoo/bot.dart
environment:
  sdk: '>=0.7.6'
dependencies:
  bot: '>=0.23.1'
  bot_web: '>=0.20.5'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.7.6'
  hop: '>=0.25.1'
