name: qr
author: Kevin Moore <github@j832.com.com>
description: A demo of generating QR codes in Dart.
homepage: https://github.com/kevmoo/qr.dart/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.28.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  test: any
transformers:
- $dart2js:
    commandLineOptions: [--dump-info, --no-frequency-based-minification]
