name: qr
version: 1.0.0
author: Kevin Moore <github@j832.com>
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
homepage: https://github.com/kevmoo/qr.dart/

environment:
  sdk: '>=2.0.0-dev.17 <2.0.0'

dev_dependencies:
  bot: ^0.28.0
  test: ^0.12.13

transformers:
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
    - --dump-info
    - --no-frequency-based-minification
    - --trust-type-annotations
    - --trust-primitives
