name: qr
author: Kevin Moore <github@j832.com.com>
description: A demo of generating QR codes in Dart.
homepage: https://github.com/kevmoo/qr.dart/
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  bot: ^0.28.0
  browser: '>=0.9.0 <0.11.0'
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.13
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
    - --dump-info
    - --no-frequency-based-minification
    - --trust-type-annotations
    - --trust-primitives
