name: qr
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.1.0
description: A demo of generating QR codes in Dart.
dependencies:
  bot:
    git:
      url: https://github.com/kevmoo/bot.dart.git
      ref: master
